name: Bundle JS and deploy in dist

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
